### ISSUE TITLE
Vimeo link fails parsing

### ISSUE THREAD

**Issue by skywalker666** [chojnicki/video-platforms-parser#13]
The vimeo link https://vimeo.com/660987348/040186c83d fails parsing. I think the problem is in VideoPlatformsParser.php:180 as the end of the path is not numeric. Probably some custom url: https://help.vimeo.com/hc/en-us/articles/12426180984465-How-to-create-a-custom-URL-for-my-video

**Comment by chojnicki** [comment]
Thanks for report. Actually issue was with other Vimeo feature - private videos (shared links with hash). It's fixed in v1.4.1
