### ISSUE TITLE
cannot retrieve dailymotion metadata

### ISSUE THREAD

**Issue by westiti** [chojnicki/video-platforms-parser#15]
I tried both API and non API requests but I couldn't retrieve  dailymotion video meta data:
URL:  https://www.dailymotion.com/video/x8jjiqy
response: [ 
  "id" => "x8jjiqy"
  "platform" => "dailymotion"
  "title" => ""
  "description" => ""
  "thumbnail" => ""
  "tags" => []
  "duration" => 0
  "api" => false
]

**Comment by chojnicki** [comment]
I can see that Dailymotion has new web app and that's why parses cannot find needed meta tags anymore.

But I cannot reproduce your problem with API enabled. Parsing HTML is always tricky and pron to errors, and that's why it is only a backup option in my tool. API should be not changed by provider, and I can confirm that after few years it is working like it should.

Result:

```
{
   "id": "x8jjiqy",
   "platform": "dailymotion",
   "title": "A bird's eye view of Broadmeadow | Newcastle Herald | March 2023",
   "description": "Source: Google Earth",
   "thumbnail": "https://s1.dmcdn.net/v/UoVYg1cn4as7KFX3K",
   "tags": ["news","business","council-news"],
   "duration": 15,
   "api": true
} 
```

1. Are you 100% sure that you tested API enabled? This is default option. Check for `api` as true in result.
2. Could you provide result for that too?
3. Is there really a result with empty properties, or maybe there is some error throwed by PHP?

**Comment by westiti** [comment]
Thanks for the quick response.

I'm using laravel and this is the method that handles the request:


public function parse(Request $request)
{

$parser = new VideoPlatformsParser(
[
'youtube_api_key' => '',
'youtube_api_disabled' => true,
'dailymotion_api_disabled' => false,
'vimeo_api_disabled' => true,
'streamable_api_disabled' => true,
'twitter_api_bearer_token' => '',
'twitter_api_disabled' => true
]
);

$id = $request->input('id');
$provider = $request->input('provider');

switch ($provider) {
case 'youtube':
$url = "https://www.youtube.com/watch?v={$id}";
break;
case 'vimeo':
$url = "https://vimeo.com/{$id}";
break;
case 'facebook':
$url = "https://www.facebook.com/watch/?v={$id}";
break;
case 'dailymotion':
$url = "https://www.dailymotion.com/video/{$id}";
break;
}

try {
$info = cache()->remember($url, now()->addDay(), fn () => $parser->get($url
));

dd($info);
if (Str::of($info['thumbnail'])->trim()->isEmpty()) {
return response(__('public.app.noThumbnailError'), 500);
}
return [
'title' => $info['title'] ?? 'Video thumbnail',
'thumbnail' => $info['thumbnail'],
'id' => $info['id'],
];
} catch (\Throwable $th) {
Log::error($th->getMessage());

return response(__('public.app.unexpectedError'), 500);
}
}

I set dailymotion_api_disabled to false and I'm still getting the same
response (I'm using dd()):


[ // app/Http/Controllers/HomeController.php:64
  "id" => "x8jjiqy"
  "platform" => "dailymotion"
  "title" => ""
  "description" => ""
  "thumbnail" => ""
  "tags" => []
  "duration" => 0
  "api" => false
]


By the way, the other platforms are working as expected

**Comment by chojnicki** [comment]
Well, you are using cache, so `remember()` even after changing config will still return old result instead running parser again. Clear cache and try again.

BTW, not related to issue, but if you are using Laravel there is no point of creating VideoPlatformsParser instance and passing config that way. There is Laravel facade support, with regular config.

**Comment by westiti** [comment]
Yes, It's working now after I cleared the cache. How could I miss that?

Again thanks for the quick response and also for the help and sorry for the
inconvenience.
